#===================================================================================================================
#  Moving Average Service API Configuration
#====================================================================================================================

info:
  app:
    name: Moving.Average.Service
    description: Moving-Average Service Configuration
    version: 1.0.0

#===================================================================================================================
#  Default Stream defined
#====================================================================================================================

defaultStream:
   defaultQueueSize: 4
   input: 
     - 5
     - 3
     - 6
     - 9
     - 4
     - 11
